/**
 * Dữ liệu dùng khi chưa cấu hình Supabase.
 *
 * ĐỌC TRỰC TIẾP TỪ supabase/seed.sql? Không — file SQL không parse được ở runtime.
 * Thay vào đó dữ liệu ở đây phản chiếu đúng seed, để giao diện chạy được đầy đủ
 * ngay từ lần clone đầu tiên và developer thấy được luồng thật trước khi có DB.
 *
 * Đây KHÔNG phải "giao diện demo tĩnh": mọi trang gọi qua cùng một interface
 * repository, đổi sang Supabase chỉ là đổi biến môi trường, không sửa component.
 */
import { fromMajorUnits } from '@/core/money';
import type { MerchantSummary, ServiceDetail } from '../types';

const desertRose: MerchantSummary = {
  id: 'e0000000-0000-4000-8000-000000000001',
  slug: 'desert-rose-tourism',
  name: 'Desert Rose Dubai',
  status: 'approved',
  isVerified: true,
  logoUrl: null,
  city: 'Dubai',
  country: 'AE',
  ratingAvg: 4.8,
  ratingCount: 214,
};

const usd = (v: number) => fromMajorUnits(v, 'USD');

export const MEMORY_CATEGORIES = [
  { id: 'd1', slug: 'day-tours',         vi: 'Tour trong ngày',        en: 'Day Tours' },
  { id: 'd2', slug: 'multi-day-tours',   vi: 'Tour nhiều ngày',        en: 'Multi-day Tours' },
  { id: 'd3', slug: 'dubai-uae-tours',   vi: 'Tour Dubai & UAE',       en: 'Dubai & UAE Tours' },
  { id: 'd4', slug: 'pilgrimage-tours',  vi: 'Tour hành hương',        en: 'Pilgrimage Tours' },
  { id: 'd5', slug: 'hotels-apartments', vi: 'Khách sạn & căn hộ',     en: 'Hotels & Apartments' },
  { id: 'd6', slug: 'attraction-tickets',vi: 'Vé tham quan',           en: 'Attraction Tickets' },
  { id: 'd7', slug: 'event-tickets',     vi: 'Vé sự kiện',             en: 'Event Tickets' },
  { id: 'd8', slug: 'theme-parks',       vi: 'Công viên giải trí',     en: 'Theme Parks' },
  { id: 'd9', slug: 'desert-safari',     vi: 'Safari sa mạc',          en: 'Desert Safari' },
  { id: 'd10',slug: 'yacht-cruise',      vi: 'Du thuyền & yacht',      en: 'Yacht & Cruise' },
  { id: 'd11',slug: 'dining-vouchers',   vi: 'Nhà hàng & voucher ăn uống', en: 'Dining & Restaurant Vouchers' },
  { id: 'd12',slug: 'airport-transfer',  vi: 'Đưa đón sân bay',        en: 'Airport Transfer' },
  { id: 'd13',slug: 'car-rental',        vi: 'Thuê xe',                en: 'Car Rental' },
  { id: 'd14',slug: 'tour-guides',       vi: 'Hướng dẫn viên',         en: 'Tour Guides' },
  { id: 'd15',slug: 'visa',              vi: 'Visa',                   en: 'Visa' },
  { id: 'd16',slug: 'flights',           vi: 'Vé máy bay',             en: 'Flights' },
  { id: 'd17',slug: 'travel-insurance',  vi: 'Bảo hiểm du lịch',       en: 'Travel Insurance' },
  { id: 'd18',slug: 'sim-esim',          vi: 'SIM & eSIM',             en: 'SIM & eSIM' },
  { id: 'd19',slug: 'photography',       vi: 'Chụp ảnh & quay phim',   en: 'Photography & Videography' },
  { id: 'd20',slug: 'other-services',    vi: 'Dịch vụ du lịch khác',   en: 'Other Travel Services' },
] as const;

interface MemoryService extends Omit<ServiceDetail, 'title' | 'summary' | 'description' | 'highlights' | 'included' | 'excluded'> {
  i18n: Record<'vi' | 'en', {
    title: string; summary: string; description: string;
    highlights: string[]; included: string[]; excluded: string[];
  }>;
}

export const MEMORY_SERVICES: MemoryService[] = [
  {
    id: 'f0000000-0000-4000-8000-000000000001',
    slug: 'evening-desert-safari-bbq',
    categorySlug: 'desert-safari',
    city: 'Dubai', country: 'AE',
    coverImageUrl: null,
    priceFrom: usd(41), durationMinutes: 360,
    languages: ['en', 'ar', 'vi'],
    instantConfirmation: true, freeCancellation: true, pickupAvailable: true,
    ratingAvg: 4.8, ratingCount: 214, bookingCount: 1840, isFeatured: true,
    merchant: desertRose,
    address: 'Lehbab Desert Conservation Area',
    latitude: 24.8271, longitude: 55.5032,
    meetingPoint: 'Đón tại khách sạn trong khu Dubai Marina / Downtown / Deira',
    minGuests: 1, maxGuests: 40,
    guestRequirements: null, healthRequirements: 'Không phù hợp với phụ nữ mang thai và người có vấn đề về cột sống.',
    bookingCutoffHours: 12,
    usageTerms: null,
    media: [], itinerary: [],
    packages: [
      { id: 'p1', code: 'standard', name: 'Tiêu chuẩn', description: 'Xe ghép tối đa 6 khách',
        priceAdult: usd(41), priceChild: usd(26), priceGroup: null, groupSize: null,
        taxRateBps: 500, minGuests: 1, maxGuests: 40 },
      { id: 'p2', code: 'vip', name: 'VIP', description: 'Xe riêng, khu ngồi VIP',
        priceAdult: usd(79), priceChild: usd(52), priceGroup: null, groupSize: null,
        taxRateBps: 500, minGuests: 1, maxGuests: 20 },
    ],
    policies: {
      cancellationText: 'Huỷ miễn phí trước 24 giờ. Trong 24 giờ hoàn 50%.',
      cancellationTiers: [{ hoursBefore: 24, refundBps: 10000 }, { hoursBefore: 4, refundBps: 5000 }],
      rescheduleAllowed: true, refundText: null, disputeWindowHours: 72,
    },
    i18n: {
      vi: {
        title: 'Safari sa mạc buổi chiều kèm tiệc BBQ',
        summary: 'Lái xe cồn cát, cưỡi lạc đà, xem hoàng hôn và bữa tối BBQ trong trại sa mạc Bedouin.',
        description: 'Xe 4x4 đón bạn tại khách sạn vào đầu giờ chiều, chạy khoảng 45 phút tới khu bảo tồn sa mạc Lehbab. Chương trình gồm 20 phút lái xe cồn cát, dừng chụp ảnh hoàng hôn, cưỡi lạc đà ngắn, vẽ henna và bữa tối BBQ buffet có món chay.',
        highlights: ['Lái xe cồn cát 20 phút với tài xế có chứng chỉ', 'Ngắm hoàng hôn giữa cồn cát đỏ', 'Bữa tối BBQ buffet có món chay và halal', 'Múa Tanoura và trình diễn lửa'],
        included: ['Đón và trả tại khách sạn', 'Nước uống không giới hạn', 'Bữa tối BBQ buffet', 'Cưỡi lạc đà', 'Vẽ henna'],
        excluded: ['Đồ uống có cồn', 'Quad bike (phụ phí 150 USD)', 'Tiền tip cho tài xế'],
      },
      en: {
        title: 'Evening Desert Safari with BBQ Dinner',
        summary: 'Dune bashing, camel ride, sunset photos and a BBQ dinner at a Bedouin camp.',
        description: 'A 4x4 collects you from your hotel in the early afternoon for the 45-minute drive to the Lehbab desert conservation area. The programme includes 20 minutes of dune bashing, a sunset photo stop, a short camel ride, henna painting and a BBQ buffet dinner with vegetarian options.',
        highlights: ['20 minutes of dune bashing with a certified driver', 'Sunset over the red dunes', 'BBQ buffet with vegetarian and halal options', 'Tanoura dance and fire show'],
        included: ['Hotel pickup and drop-off', 'Unlimited soft drinks', 'BBQ buffet dinner', 'Camel ride', 'Henna painting'],
        excluded: ['Alcoholic beverages', 'Quad bike (150 USD supplement)', 'Driver gratuities'],
      },
    },
  },
  {
    id: 'f0000000-0000-4000-8000-000000000002',
    slug: 'burj-khalifa-124-125-floor',
    categorySlug: 'attraction-tickets',
    city: 'Dubai', country: 'AE',
    coverImageUrl: null,
    priceFrom: usd(49), durationMinutes: 90,
    languages: ['en', 'ar', 'vi'],
    instantConfirmation: true, freeCancellation: false, pickupAvailable: false,
    ratingAvg: 4.7, ratingCount: 3120, bookingCount: 9400, isFeatured: true,
    merchant: desertRose,
    address: '1 Sheikh Mohammed bin Rashid Blvd',
    latitude: 25.197197, longitude: 55.274376,
    meetingPoint: 'Quầy At The Top, tầng hầm Dubai Mall',
    minGuests: 1, maxGuests: 10,
    guestRequirements: null, healthRequirements: null, bookingCutoffHours: 24,
    usageTerms: null,
    media: [], itinerary: [],
    packages: [
      { id: 'p3', code: 'standard', name: 'Giờ thường', description: 'Khung giờ ban ngày',
        priceAdult: usd(49), priceChild: usd(41), priceGroup: null, groupSize: null,
        taxRateBps: 500, minGuests: 1, maxGuests: 10 },
      { id: 'p4', code: 'sunset', name: 'Giờ hoàng hôn', description: 'Khung giờ đẹp nhất',
        priceAdult: usd(71), priceChild: usd(60), priceGroup: null, groupSize: null,
        taxRateBps: 500, minGuests: 1, maxGuests: 10 },
    ],
    policies: {
      cancellationText: 'Vé đã xuất không hoàn, không đổi ngày.',
      cancellationTiers: [], rescheduleAllowed: false, refundText: null, disputeWindowHours: 48,
    },
    i18n: {
      vi: {
        title: 'Vé Burj Khalifa tầng 124 & 125',
        summary: 'Lên đài quan sát toà nhà cao nhất thế giới, vào cửa không xếp hàng.',
        description: 'Vé vào cửa tầng 124 và 125 của Burj Khalifa. Thang máy tốc độ cao đưa bạn lên độ cao 452 m trong khoảng 1 phút. Khung giờ hoàng hôn kín chỗ rất sớm, nên đặt trước ít nhất 3 ngày.',
        highlights: ['Vào cửa không xếp hàng', 'Đài quan sát ngoài trời tầng 124', 'Kính viễn vọng thực tế tăng cường'],
        included: ['Vé vào cửa tầng 124 và 125', 'Hướng dẫn đa ngôn ngữ qua ứng dụng'],
        excluded: ['Đưa đón', 'Đồ ăn thức uống', 'Vé tầng 148'],
      },
      en: {
        title: 'Burj Khalifa Level 124 & 125 Ticket',
        summary: "Skip-the-line access to the observation decks of the world's tallest building.",
        description: 'Admission to levels 124 and 125 of the Burj Khalifa. A high-speed lift takes you to 452 m in about a minute. Sunset slots sell out well in advance — book at least three days ahead.',
        highlights: ['Skip-the-line entry', 'Outdoor observation terrace on level 124', 'Augmented-reality telescopes'],
        included: ['Admission to levels 124 and 125', 'Multilingual guide via app'],
        excluded: ['Transfers', 'Food and drink', 'Level 148 access'],
      },
    },
  },
  {
    id: 'f0000000-0000-4000-8000-000000000003',
    slug: 'dubai-marina-luxury-yacht',
    categorySlug: 'yacht-cruise',
    city: 'Dubai', country: 'AE',
    coverImageUrl: null,
    priceFrom: usd(123), durationMinutes: 120,
    languages: ['en', 'ar'],
    instantConfirmation: false, freeCancellation: true, pickupAvailable: false,
    ratingAvg: 4.9, ratingCount: 86, bookingCount: 310, isFeatured: true,
    merchant: desertRose,
    address: 'Dubai Marina Yacht Club',
    latitude: 25.0806, longitude: 55.1403,
    meetingPoint: 'Bến số 3, Dubai Marina Yacht Club',
    minGuests: 2, maxGuests: 12,
    guestRequirements: null, healthRequirements: null, bookingCutoffHours: 48,
    usageTerms: null,
    media: [], itinerary: [],
    packages: [
      { id: 'p5', code: 'charter2h', name: 'Thuê nguyên thuyền 2 giờ', description: 'Trọn gói tối đa 12 khách',
        priceAdult: usd(0), priceChild: null, priceGroup: usd(395), groupSize: 12,
        taxRateBps: 500, minGuests: 2, maxGuests: 12 },
    ],
    policies: {
      cancellationText: 'Huỷ miễn phí trước 48 giờ. Thời tiết xấu được đổi lịch miễn phí.',
      cancellationTiers: [{ hoursBefore: 48, refundBps: 10000 }, { hoursBefore: 24, refundBps: 5000 }],
      rescheduleAllowed: true, refundText: null, disputeWindowHours: 72,
    },
    i18n: {
      vi: {
        title: 'Thuê du thuyền riêng Dubai Marina 2 giờ',
        summary: 'Du thuyền riêng cho nhóm tới 12 khách, đi qua Marina, JBR và Ain Dubai.',
        description: 'Du thuyền dài 48 feet có khoang lạnh, sân tắm nắng và nhà vệ sinh. Hải trình 2 giờ có dừng để bơi và chụp ảnh. Khách được mang đồ ăn thức uống riêng.',
        highlights: ['Du thuyền riêng, không ghép khách', 'Thuyền trưởng và thuỷ thủ đoàn có bằng', 'Dừng bơi giữa hải trình'],
        included: ['Du thuyền riêng 2 giờ', 'Thuyền trưởng và thuỷ thủ đoàn', 'Nước suối và đá', 'Áo phao'],
        excluded: ['Đồ ăn và đồ uống', 'Đưa đón', 'Thiết bị câu cá'],
      },
      en: {
        title: 'Private Dubai Marina Yacht Charter — 2 Hours',
        summary: 'A private yacht for up to 12 guests along the Marina, JBR and Ain Dubai.',
        description: 'A 48-foot yacht with an air-conditioned cabin, sun deck and bathroom. The two-hour route includes a stop for swimming and photos. You are welcome to bring your own food and drinks.',
        highlights: ['Private charter, no shared groups', 'Licensed captain and crew', 'Mid-route swimming stop'],
        included: ['Two-hour private charter', 'Captain and crew', 'Bottled water and ice', 'Life jackets'],
        excluded: ['Food and beverages', 'Transfers', 'Fishing equipment'],
      },
    },
  },
  {
    id: 'f0000000-0000-4000-8000-000000000004',
    slug: 'dxb-airport-transfer-private',
    categorySlug: 'airport-transfer',
    city: 'Dubai', country: 'AE',
    coverImageUrl: null,
    priceFrom: usd(33), durationMinutes: 60,
    languages: ['en', 'ar', 'vi'],
    instantConfirmation: true, freeCancellation: true, pickupAvailable: true,
    ratingAvg: 4.9, ratingCount: 640, bookingCount: 4100, isFeatured: false,
    merchant: desertRose,
    address: 'Dubai International Airport',
    latitude: 25.2528, longitude: 55.3644,
    meetingPoint: 'Sảnh đến, nhân viên cầm bảng tên khách',
    minGuests: 1, maxGuests: 6,
    guestRequirements: null, healthRequirements: null, bookingCutoffHours: 6,
    usageTerms: null,
    media: [], itinerary: [],
    packages: [
      { id: 'p6', code: 'sedan', name: 'Xe 4 chỗ', description: 'Lexus ES hoặc tương đương',
        priceAdult: usd(0), priceChild: null, priceGroup: usd(33), groupSize: 3,
        taxRateBps: 500, minGuests: 1, maxGuests: 3 },
      { id: 'p7', code: 'van', name: 'Xe 7 chỗ', description: 'Toyota Previa hoặc tương đương',
        priceAdult: usd(0), priceChild: null, priceGroup: usd(52), groupSize: 6,
        taxRateBps: 500, minGuests: 1, maxGuests: 6 },
    ],
    policies: {
      cancellationText: 'Huỷ miễn phí trước 6 giờ.',
      cancellationTiers: [{ hoursBefore: 6, refundBps: 10000 }],
      rescheduleAllowed: true, refundText: null, disputeWindowHours: 48,
    },
    i18n: {
      vi: {
        title: 'Đưa đón sân bay Dubai (DXB) xe riêng',
        summary: 'Tài xế đón tận sảnh đến, theo dõi chuyến bay, xe riêng không ghép khách.',
        description: 'Dịch vụ đưa đón một chiều giữa sân bay quốc tế Dubai và khách sạn trong nội thành. Tài xế theo dõi số hiệu chuyến bay nên chuyến trễ vẫn được đón. Chờ miễn phí 60 phút với chuyến quốc tế.',
        highlights: ['Theo dõi chuyến bay, trễ vẫn đón', 'Chờ miễn phí 60 phút', 'Xe riêng, không ghép khách'],
        included: ['Đón tận sảnh đến có bảng tên', 'Phí cầu đường và đỗ xe', 'Nước suối', 'Wi-Fi trên xe'],
        excluded: ['Tiền tip', 'Phí chờ quá 60 phút'],
      },
      en: {
        title: 'Dubai Airport (DXB) Private Transfer',
        summary: 'Meet-and-greet at arrivals, flight tracking, private vehicle.',
        description: 'One-way private transfer between Dubai International Airport and your hotel. Your driver tracks your flight number, so delays are covered. Sixty minutes of free waiting on international arrivals.',
        highlights: ['Flight tracking — delays covered', '60 minutes free waiting time', 'Private vehicle, no sharing'],
        included: ['Meet and greet with name board', 'All tolls and parking', 'Bottled water', 'On-board Wi-Fi'],
        excluded: ['Gratuities', 'Waiting beyond 60 minutes'],
      },
    },
  },
  {
    id: 'f0000000-0000-4000-8000-000000000005',
    slug: 'abu-dhabi-full-day-tour',
    categorySlug: 'day-tours',
    city: 'Dubai', country: 'AE',
    coverImageUrl: null,
    priceFrom: usd(76), durationMinutes: 600,
    languages: ['en', 'ar', 'vi'],
    instantConfirmation: false, freeCancellation: true, pickupAvailable: true,
    ratingAvg: 4.6, ratingCount: 452, bookingCount: 2300, isFeatured: true,
    merchant: desertRose,
    address: 'Khởi hành từ Dubai',
    latitude: 25.2048, longitude: 55.2708,
    meetingPoint: 'Đón tại khách sạn ở Dubai',
    minGuests: 2, maxGuests: 25,
    guestRequirements: 'Cần trang phục kín đáo khi vào thánh đường.',
    healthRequirements: null, bookingCutoffHours: 24,
    usageTerms: null,
    media: [], itinerary: [],
    packages: [
      { id: 'p8', code: 'join', name: 'Tour ghép', description: 'Xe chung, khởi hành hằng ngày',
        priceAdult: usd(76), priceChild: usd(52), priceGroup: null, groupSize: null,
        taxRateBps: 500, minGuests: 2, maxGuests: 25 },
    ],
    policies: {
      cancellationText: 'Huỷ miễn phí trước 24 giờ.',
      cancellationTiers: [{ hoursBefore: 24, refundBps: 10000 }, { hoursBefore: 12, refundBps: 5000 }],
      rescheduleAllowed: true, refundText: null, disputeWindowHours: 72,
    },
    i18n: {
      vi: {
        title: 'Tour Abu Dhabi trọn ngày từ Dubai',
        summary: 'Thánh đường Sheikh Zayed, Qasr Al Watan và bến Corniche trong một ngày.',
        description: 'Khởi hành từ Dubai lúc 08:00, đi khoảng 90 phút tới Abu Dhabi. Tham quan Thánh đường Lớn Sheikh Zayed, cung điện Qasr Al Watan, dừng chụp ảnh tại Emirates Palace. Về tới Dubai khoảng 19:00.',
        highlights: ['Thánh đường Lớn Sheikh Zayed', 'Cung điện Qasr Al Watan', 'Emirates Palace và bến Corniche'],
        included: ['Xe có điều hoà và đón tại khách sạn', 'Hướng dẫn viên', 'Vé vào Qasr Al Watan', 'Ăn trưa buffet'],
        excluded: ['Trang phục phù hợp thánh đường', 'Chi tiêu cá nhân', 'Tiền tip'],
      },
      en: {
        title: 'Abu Dhabi Full-Day Tour from Dubai',
        summary: 'Sheikh Zayed Grand Mosque, Qasr Al Watan and the Corniche in one day.',
        description: 'Departing Dubai at 08:00 for the 90-minute drive to Abu Dhabi. The day covers the Sheikh Zayed Grand Mosque, the Qasr Al Watan palace and a photo stop at Emirates Palace. Back in Dubai around 19:00.',
        highlights: ['Sheikh Zayed Grand Mosque', 'Qasr Al Watan palace', 'Emirates Palace and the Corniche'],
        included: ['Air-conditioned vehicle with hotel pickup', 'Guide', 'Qasr Al Watan admission', 'Buffet lunch'],
        excluded: ['Mosque-appropriate clothing', 'Personal expenses', 'Gratuities'],
      },
    },
  },
  {
    id: 'f0000000-0000-4000-8000-000000000006',
    slug: 'pierchic-seafood-dinner-voucher',
    categorySlug: 'dining-vouchers',
    city: 'Dubai', country: 'AE',
    coverImageUrl: null,
    priceFrom: usd(106), durationMinutes: 120,
    languages: ['en'],
    instantConfirmation: true, freeCancellation: false, pickupAvailable: false,
    ratingAvg: 4.8, ratingCount: 128, bookingCount: 420, isFeatured: false,
    merchant: desertRose,
    address: 'Al Qasr, Madinat Jumeirah',
    latitude: 25.1326, longitude: 55.1846,
    meetingPoint: 'Nhà hàng Pierchic, quầy lễ tân',
    minGuests: 1, maxGuests: 8,
    guestRequirements: 'Cần đặt bàn trước. Không áp dụng dịp lễ tết.',
    healthRequirements: null, bookingCutoffHours: 24,
    usageTerms: 'Voucher có giá trị 90 ngày kể từ ngày phát hành.',
    media: [], itinerary: [],
    packages: [
      { id: 'p9', code: 'set3course', name: 'Set 3 món cho 2 người', description: 'Khai vị, món chính, tráng miệng',
        priceAdult: usd(0), priceChild: null, priceGroup: usd(106), groupSize: 2,
        taxRateBps: 500, minGuests: 1, maxGuests: 8 },
    ],
    policies: {
      cancellationText: 'Voucher không hoàn tiền sau khi phát hành, có thể chuyển nhượng.',
      cancellationTiers: [], rescheduleAllowed: false, refundText: null, disputeWindowHours: 168,
    },
    i18n: {
      vi: {
        title: 'Voucher hải sản Pierchic — set 3 món cho 2 người',
        summary: 'Nhà hàng hải sản trên cầu cảng nhìn ra Burj Al Arab.',
        description: 'Set thực đơn 3 món cho hai người tại Pierchic, nhà hàng hải sản nằm cuối cầu gỗ vươn ra biển thuộc khu Madinat Jumeirah, nhìn thẳng Burj Al Arab.',
        highlights: ['Bàn nhìn ra Burj Al Arab', 'Set 3 món cho 2 người', 'Hải sản đánh bắt trong ngày'],
        included: ['Khai vị, món chính, tráng miệng cho 2 người', 'Nước lọc'],
        excluded: ['Đồ uống có cồn', 'Phí phục vụ', 'Đưa đón'],
      },
      en: {
        title: 'Pierchic Seafood Voucher — 3-Course Set for Two',
        summary: 'Pier-end seafood restaurant looking across to the Burj Al Arab.',
        description: 'A three-course set menu for two at Pierchic, a seafood restaurant at the end of a wooden pier in Madinat Jumeirah, facing the Burj Al Arab.',
        highlights: ['Table with Burj Al Arab views', 'Three courses for two', 'Daily seafood catch'],
        included: ['Starter, main and dessert for two', 'Still water'],
        excluded: ['Alcoholic beverages', 'Service charge', 'Transfers'],
      },
    },
  },
];
